config/routes.rb
Rails.application.routes.draw do
  root 'currencies#index'

  namespace :admin do
    root 'currencies#index'
    resources :currencies, only: %i[create update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  validates :value, presence: true, numericality: true, format: { with: /\A\d{1,3}(\.\d{0,4})?\z/ }

  def self.active
    find_by(active: true)
  end

  def self.forced
    active if active.try(:expiration_date).present?
  end
end

app/controllers/admin/currencies_controller.rb
module Admin
  class CurrenciesController < ApplicationController
    def index
      @currency = Currency.forced || Currency.new
    end

    def create
      result = Currencies::Create.call(params: currency_params, active: true)
      @currency = result.currency
      redirect_or_render(result)
    end

    def update
      result = Currencies::Update.call(currency_id: params[:id], params: currency_params)
      @currency = result.currency
      redirect_or_render(result)
    end

    private

    def currency_params
      params.require(:currency).permit(:value, :expiration_date)
    end

    def redirect_or_render(result)
      if result.success?
        flash[:notice] = I18n.t('ui.save_success')
        redirect_to :admin_root
      else
        flash.now[:alert] = I18n.t('ui.save_failure')
        render :index
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    @presenter = CurrencyPresenter.new(currency) if currency.present?
  end

  private

  def currency
    @currency ||= Currency.active
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-danger'
    when :alert then 'alert alert-danger'
    end
  end
end

app/views/admin/currencies/_form.html.slim
.card.col-md-7.offset-md-2
  .card-body
    .card-title
      .logout.text-right
        = link_to 'Home page', root_path

    == render 'shared/messages'
    = simple_form_for([:admin, @currency], html: {class: 'deck'}) do |f|
      = f.input :value, placeholder: '00.0000'
      = f.input :expiration_date
      = f.submit nil, class: "btn btn-#{@currency.persisted? ? 'success' : 'primary'}"

app/views/admin/currencies/index.html.slim
== render 'form'

app/views/currencies/index.html.slim
.col-md-6.offset-md-4
  .admin.text-right.mw-22
    = link_to 'Admin panel', admin_root_path
  .card.mw-22
    .card-header
      b= I18n.t('ui.currency_header')

    .card-body.text-center.font-weight-light
      card-title.currency-value
        - if @presenter.present?
          span= '1 USD ⇄ '
          = @presenter.rub_value
        - else
          = I18n.t('ui.currency_not_exist')

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv=("Content-Type")
    meta name=("viewport") content=("width=device-width, initial-scale=1")
    title FunboxCurrency
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = yield

app/views/shared/_messages.html.slim
- flash.each do |key, value|
  div(class="#{flash_class(key)}")
    = value